FROM python:3.8.5
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
RUN mkdir /code/accounts
WORKDIR /code/accounts
COPY requirements.txt /code/accounts
RUN pip3 install -r requirements.txt
COPY . /code/accounts

ENV PYTHONDONTWRITEBYTECODE=1

RUN poetry install

ENV PYTHONPATH "${PYTHONPATH}:/code"
