version: "3"
services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - fastalchdata:/var/lib/postgresql/data/
  web:
    build:
      context: .
    restart: always
    command: poetry run uvicorn app.main:app --reload --host 0.0.0.0
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  fastalchdata:
