FROM python:3.8.5
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
RUN mkdir /code/app
WORKDIR /code/app
COPY requirements.txt /code/app
RUN pip3 install -r requirements.txt
COPY . /code/app

ENV PYTHONDONTWRITEBYTECODE=1

RUN poetry install

ENV PYTHONPATH "${PYTHONPATH}:/code"
